#!/bin/bash

printf "\e[1;94m        _             \e[1;95m         _      _              \n"
printf "\e[1;94m       | | __         \e[1;95m        (_)    | |             \n"
printf "\e[1;94m  __   |__/ /         \e[1;95m__    __ _  ___| | ____  ____  \n"
printf "\e[1;94m  \ \  / / /   _____  \e[1;95m\ \  / /| |/ __  |/ __ \/    \ \n"
printf "\e[1;94m   \ \/ /  \  |\e[1;95m_____|  \ \/ / | | (__| |  ___/  () | \n"
printf "\e[1;94m    \__/_|\_\         \e[1;95m  \__/  |_|\___._|\____|\____/ \n"                                                                                                                                                                                                                                                                                    
printf "\e[0m\n"

printf "\n\e[1;95m  установка/обновление Python\e[0m\n"
pkg install python

printf "\n\e[1;95m  копирование vk-video в корневую папку\e[0m\n"
cp vk-video /data/data/com.termux/files/usr/bin
cd /data/data/com.termux/files/usr/bin
chmod +x vk-video


printf "\n\e[1;95m  установка завершена\e[0m\n"
printf "\n\e[1;93m  для запуска введите: \e[1;96mvk-video\n\n"
